//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/screamingwhale/RiderProjects/IDE_dev/IDE_dev/antlr/Pascal.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class Pascal : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Symbol=1, Comment=2, Identifier=3, Number=4, CharacterString=5;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Symbol", "Letter", "Decimal", "Hex", "Comment", "SingleLineComment", 
		"MultiLineComment", "NestedComment", "Identifier", "UNDERSCORE", "Number", 
		"UnsignedNumber", "UnsignedInteger", "Sign", "PLUS", "MINUS", "DecimalSequence", 
		"DOLLAR", "HexSequence", "AMPERSAND", "OctalSequence", "Octal", "PERCENT", 
		"BinarySequence", "Binary", "UnsignedReal", "Dot", "ScaleFactor", "E", 
		"CharacterString", "QuotedString", "StringCharacter", "QUOTE", "ControlString", 
		"HASH"
	};


	public Pascal(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Pascal(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "Symbol", "Comment", "Identifier", "Number", "CharacterString"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Pascal.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Pascal() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex) {
		switch (ruleIndex) {
		case 8 : Identifier_action(_localctx, actionIndex); break;
		}
	}
	private void Identifier_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 0: 0,126 break;
		}
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\a', '\xF0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x5', '\x2', 'M', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'W', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\a', '\a', ']', '\n', '\a', '\f', '\a', '\xE', '\a', 
		'`', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', 'm', '\n', '\b', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', 'q', '\n', '\t', '\f', '\t', '\xE', '\t', 't', '\v', '\t', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', 'x', '\n', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x5', '\n', '}', '\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x5', '\f', '\x84', '\n', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x8A', '\n', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x5', '\xE', '\x96', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\x9A', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x6', '\x12', '\xA1', '\n', '\x12', '\r', 
		'\x12', '\xE', '\x12', '\xA2', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x6', '\x14', '\xA8', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\xA9', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x6', '\x16', '\xAF', '\n', 
		'\x16', '\r', '\x16', '\xE', '\x16', '\xB0', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x6', '\x19', '\xB8', '\n', 
		'\x19', '\r', '\x19', '\xE', '\x19', '\xB9', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', 
		'\xC2', '\n', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\xC5', '\n', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', 
		'\xCB', '\n', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x6', '\x1F', '\xD3', '\n', '\x1F', 
		'\r', '\x1F', '\xE', '\x1F', '\xD4', '\x3', ' ', '\x3', ' ', '\a', ' ', 
		'\xD9', '\n', ' ', '\f', ' ', '\xE', ' ', '\xDC', '\v', ' ', '\x3', ' ', 
		'\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', 
		'\xE4', '\n', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x6', '#', '\xEB', '\n', '#', '\r', '#', '\xE', '#', '\xEC', '\x3', 
		'$', '\x3', '$', '\x3', 'r', '\x2', '%', '\x3', '\x3', '\x5', '\x2', '\a', 
		'\x2', '\t', '\x2', '\v', '\x4', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', 
		'\x13', '\x5', '\x15', '\x2', '\x17', '\x6', '\x19', '\x2', '\x1B', '\x2', 
		'\x1D', '\x2', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', 
		'\x2', ')', '\x2', '+', '\x2', '-', '\x2', '/', '\x2', '\x31', '\x2', 
		'\x33', '\x2', '\x35', '\x2', '\x37', '\x2', '\x39', '\x2', ';', '\x2', 
		'=', '\a', '?', '\x2', '\x41', '\x2', '\x43', '\x2', '\x45', '\x2', 'G', 
		'\x2', '\x3', '\x2', '\n', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', '\x2', '\x32', '\x39', 
		'\x3', '\x2', '\x32', '\x33', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', 
		'\x2', '\f', '\f', ')', ')', '\x2', '\xED', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x3', 'L', '\x3', '\x2', '\x2', 
		'\x2', '\x5', 'N', '\x3', '\x2', '\x2', '\x2', '\a', 'P', '\x3', '\x2', 
		'\x2', '\x2', '\t', 'R', '\x3', '\x2', '\x2', '\x2', '\v', 'V', '\x3', 
		'\x2', '\x2', '\x2', '\r', 'X', '\x3', '\x2', '\x2', '\x2', '\xF', 'l', 
		'\x3', '\x2', '\x2', '\x2', '\x11', 'r', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'w', '\x3', '\x2', '\x2', '\x2', '\x15', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x83', '\x3', '\x2', '\x2', '\x2', '\x19', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x95', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x9D', '\x3', '\x2', '\x2', '\x2', '#', '\xA0', '\x3', '\x2', 
		'\x2', '\x2', '%', '\xA4', '\x3', '\x2', '\x2', '\x2', '\'', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', ')', '\xAB', '\x3', '\x2', '\x2', '\x2', '+', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xB2', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\x31', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xBB', '\x3', '\x2', '\x2', '\x2', '\x35', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\xC6', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', ';', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '=', '\xD2', '\x3', '\x2', '\x2', '\x2', '?', '\xD6', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\xE3', '\x3', '\x2', '\x2', '\x2', '\x43', '\xE5', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\xEA', '\x3', '\x2', '\x2', '\x2', 
		'G', '\xEE', '\x3', '\x2', '\x2', '\x2', 'I', 'M', '\x5', '\x5', '\x3', 
		'\x2', 'J', 'M', '\x5', '\a', '\x4', '\x2', 'K', 'M', '\x5', '\t', '\x5', 
		'\x2', 'L', 'I', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'K', '\x3', '\x2', '\x2', '\x2', 'M', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'O', '\t', '\x2', '\x2', '\x2', 'O', '\x6', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'Q', '\t', '\x3', '\x2', '\x2', 'Q', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'S', '\t', '\x4', '\x2', '\x2', 'S', '\n', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'W', '\x5', '\r', '\a', '\x2', 'U', 'W', '\x5', 
		'\xF', '\b', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'W', '\f', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', 
		'\a', '\x31', '\x2', '\x2', 'Y', 'Z', '\a', '\x31', '\x2', '\x2', 'Z', 
		'^', '\x3', '\x2', '\x2', '\x2', '[', ']', '\n', '\x5', '\x2', '\x2', 
		'\\', '[', '\x3', '\x2', '\x2', '\x2', ']', '`', '\x3', '\x2', '\x2', 
		'\x2', '^', '\\', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', 
		'\x2', '\x2', '_', '\xE', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\a', '}', '\x2', '\x2', '\x62', 
		'\x63', '\x5', '\x11', '\t', '\x2', '\x63', '\x64', '\a', '\x7F', '\x2', 
		'\x2', '\x64', 'm', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', 
		'*', '\x2', '\x2', '\x66', 'g', '\a', ',', '\x2', '\x2', 'g', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'h', 'i', '\x5', '\x11', '\t', '\x2', 'i', 'j', '\a', 
		',', '\x2', '\x2', 'j', 'k', '\a', '+', '\x2', '\x2', 'k', 'm', '\x3', 
		'\x2', '\x2', '\x2', 'l', '\x61', '\x3', '\x2', '\x2', '\x2', 'l', '\x65', 
		'\x3', '\x2', '\x2', '\x2', 'm', '\x10', '\x3', '\x2', '\x2', '\x2', 'n', 
		'q', '\x5', '\xF', '\b', '\x2', 'o', 'q', '\v', '\x2', '\x2', '\x2', 'p', 
		'n', '\x3', '\x2', '\x2', '\x2', 'p', 'o', '\x3', '\x2', '\x2', '\x2', 
		'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 's', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'x', '\x5', '\x5', '\x3', 
		'\x2', 'v', 'x', '\x5', '\x15', '\v', '\x2', 'w', 'u', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'v', '\x3', '\x2', '\x2', '\x2', 'x', '|', '\x3', '\x2', '\x2', 
		'\x2', 'y', '}', '\x5', '\x5', '\x3', '\x2', 'z', '}', '\x5', '\a', '\x4', 
		'\x2', '{', '}', '\x5', '\x15', '\v', '\x2', '|', 'y', '\x3', '\x2', '\x2', 
		'\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', '|', '{', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\b', '\n', 
		'\x2', '\x2', '\x7F', '\x14', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\x61', '\x2', '\x2', '\x81', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x84', '\x5', '\x1D', '\xF', '\x2', '\x83', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x5', '\x19', '\r', '\x2', 
		'\x86', '\x18', '\x3', '\x2', '\x2', '\x2', '\x87', '\x8A', '\x5', '\x1B', 
		'\xE', '\x2', '\x88', '\x8A', '\x5', '\x35', '\x1B', '\x2', '\x89', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x96', '\x5', '#', 
		'\x12', '\x2', '\x8C', '\x8D', '\x5', '%', '\x13', '\x2', '\x8D', '\x8E', 
		'\x5', '\'', '\x14', '\x2', '\x8E', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x90', '\x5', ')', '\x15', '\x2', '\x90', '\x91', '\x5', '+', 
		'\x16', '\x2', '\x91', '\x96', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', 
		'\x5', '/', '\x18', '\x2', '\x93', '\x94', '\x5', '\x31', '\x19', '\x2', 
		'\x94', '\x96', '\x3', '\x2', '\x2', '\x2', '\x95', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x95', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x95', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', '\x5', '\x1F', 
		'\x10', '\x2', '\x98', '\x9A', '\x5', '!', '\x11', '\x2', '\x99', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x98', '\x3', '\x2', '\x2', '\x2', 
		'\x9A', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '-', 
		'\x2', '\x2', '\x9C', ' ', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', '/', '\x2', '\x2', '\x9E', '\"', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA1', '\x5', '\a', '\x4', '\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '&', '\x2', '\x2', 
		'\xA5', '&', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA8', '\x5', '\t', 
		'\x5', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '(', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xAC', '\a', '(', '\x2', '\x2', '\xAC', '*', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xAF', '\x5', '-', '\x17', '\x2', '\xAE', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', ',', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\t', '\x6', '\x2', '\x2', '\xB3', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xB4', '\xB5', '\a', '\'', '\x2', '\x2', '\xB5', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\xB6', '\xB8', '\x5', '\x33', '\x1A', '\x2', '\xB7', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', '\xBA', '\x32', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', 
		'\t', '\a', '\x2', '\x2', '\xBC', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\xC1', '\x5', '#', '\x12', '\x2', '\xBE', '\xBF', '\x5', '\x37', 
		'\x1C', '\x2', '\xBF', '\xC0', '\x5', '#', '\x12', '\x2', '\xC0', '\xC2', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xBE', '\x3', '\x2', '\x2', '\x2', 
		'\xC1', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC4', '\x3', '\x2', 
		'\x2', '\x2', '\xC3', '\xC5', '\x5', '\x39', '\x1D', '\x2', '\xC4', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', 
		'\xC5', '\x36', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\a', '\x30', 
		'\x2', '\x2', '\xC7', '\x38', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xCA', 
		'\x5', ';', '\x1E', '\x2', '\xC9', '\xCB', '\x5', '\x1D', '\xF', '\x2', 
		'\xCA', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', '\x2', 
		'\x2', '\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', 
		'\x5', '#', '\x12', '\x2', '\xCD', ':', '\x3', '\x2', '\x2', '\x2', '\xCE', 
		'\xCF', '\t', '\b', '\x2', '\x2', '\xCF', '<', '\x3', '\x2', '\x2', '\x2', 
		'\xD0', '\xD3', '\x5', '?', ' ', '\x2', '\xD1', '\xD3', '\x5', '\x45', 
		'#', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD1', 
		'\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\x3', '\x2', '\x2', '\x2', 
		'\xD4', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', '\x2', 
		'\x2', '\x2', '\xD5', '>', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xDA', 
		'\x5', '\x43', '\"', '\x2', '\xD7', '\xD9', '\x5', '\x41', '!', '\x2', 
		'\xD8', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDC', '\x3', '\x2', 
		'\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', 
		'\x3', '\x2', '\x2', '\x2', '\xDB', '\xDD', '\x3', '\x2', '\x2', '\x2', 
		'\xDC', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x5', '\x43', 
		'\"', '\x2', '\xDE', '@', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE4', 
		'\n', '\t', '\x2', '\x2', '\xE0', '\xE1', '\x5', '\x43', '\"', '\x2', 
		'\xE1', '\xE2', '\x5', '\x43', '\"', '\x2', '\xE2', '\xE4', '\x3', '\x2', 
		'\x2', '\x2', '\xE3', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE0', 
		'\x3', '\x2', '\x2', '\x2', '\xE4', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\xE5', '\xE6', '\a', ')', '\x2', '\x2', '\xE6', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\xE7', '\xE8', '\x5', 'G', '$', '\x2', '\xE8', '\xE9', 
		'\x5', '\x1B', '\xE', '\x2', '\xE9', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\xEA', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\x3', '\x2', 
		'\x2', '\x2', '\xEC', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', 
		'\x3', '\x2', '\x2', '\x2', '\xED', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\xEE', '\xEF', '\a', '%', '\x2', '\x2', '\xEF', 'H', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x2', 'L', 'V', '^', 'l', 'p', 'r', 'w', '|', '\x83', 
		'\x89', '\x95', '\x99', '\xA2', '\xA9', '\xB0', '\xB9', '\xC1', '\xC4', 
		'\xCA', '\xD2', '\xD4', '\xDA', '\xE3', '\xEC', '\x3', '\x3', '\n', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
