//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/screamingwhale/RiderProjects/IDE_dev/IDE_dev/antlr/Pascal.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class Pascal : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Symbol=1, Comment=2, Identifier=3, Number=4, CharacterString=5, Whitespace=6, 
		SEMICOLON=7, LBRC=8, RBRC=9, DOT=10, Error=11;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Symbol", "Letter", "Decimal", "Hex", "Comment", "SingleLineComment", 
		"MultiLineComment", "NestedComment", "Identifier", "UNDERSCORE", "Number", 
		"UnsignedNumber", "UnsignedInteger", "Sign", "PLUS", "MINUS", "DecimalSequence", 
		"DOLLAR", "HexSequence", "AMPERSAND", "OctalSequence", "Octal", "PERCENT", 
		"BinarySequence", "Binary", "UnsignedReal", "Dot", "ScaleFactor", "E", 
		"CharacterString", "QuotedString", "StringCharacter", "QUOTE", "ControlString", 
		"HASH", "Whitespace", "SEMICOLON", "LBRC", "RBRC", "DOT", "Error"
	};


	public Pascal(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Pascal(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "';'", "'('", "')'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Symbol", "Comment", "Identifier", "Number", "CharacterString", 
		"Whitespace", "SEMICOLON", "LBRC", "RBRC", "DOT", "Error"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Pascal.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Pascal() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex) {
		switch (ruleIndex) {
		case 8 : Identifier_action(_localctx, actionIndex); break;
		}
	}
	private void Identifier_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 0: 0,126 break;
		}
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\r', '\x10E', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x5', '\x2', 'Y', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', '\x63', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\a', '\a', 'i', '\n', '\a', '\f', '\a', '\xE', '\a', 'l', 
		'\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', 'y', '\n', '\b', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', '}', '\n', '\t', '\f', '\t', '\xE', '\t', '\x80', '\v', '\t', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', '\x84', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', '\x89', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x5', '\f', '\x90', '\n', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', 
		'\x96', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x5', '\xE', '\xA2', '\n', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', '\xA6', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x6', '\x12', '\xAD', '\n', 
		'\x12', '\r', '\x12', '\xE', '\x12', '\xAE', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x6', '\x14', '\xB4', '\n', '\x14', '\r', '\x14', '\xE', 
		'\x14', '\xB5', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x6', '\x16', 
		'\xBB', '\n', '\x16', '\r', '\x16', '\xE', '\x16', '\xBC', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x6', '\x19', 
		'\xC4', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xC5', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x5', '\x1B', '\xCE', '\n', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\xD1', 
		'\n', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', 
		'\x5', '\x1D', '\xD7', '\n', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x6', '\x1F', '\xDF', 
		'\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', '\xE0', '\x3', ' ', '\x3', 
		' ', '\a', ' ', '\xE5', '\n', ' ', '\f', ' ', '\xE', ' ', '\xE8', '\v', 
		' ', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', 
		'!', '\x5', '!', '\xF0', '\n', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', 
		'\x3', '#', '\x3', '#', '\x6', '#', '\xF7', '\n', '#', '\r', '#', '\xE', 
		'#', '\xF8', '\x3', '$', '\x3', '$', '\x3', '%', '\x6', '%', '\xFE', '\n', 
		'%', '\r', '%', '\xE', '%', '\xFF', '\x3', '&', '\x3', '&', '\x3', '\'', 
		'\x3', '\'', '\x3', '(', '\x3', '(', '\x3', ')', '\x3', ')', '\x3', '*', 
		'\x6', '*', '\x10B', '\n', '*', '\r', '*', '\xE', '*', '\x10C', '\x4', 
		'~', '\x10C', '\x2', '+', '\x3', '\x3', '\x5', '\x2', '\a', '\x2', '\t', 
		'\x2', '\v', '\x4', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', 
		'\x5', '\x15', '\x2', '\x17', '\x6', '\x19', '\x2', '\x1B', '\x2', '\x1D', 
		'\x2', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', '\x2', 
		')', '\x2', '+', '\x2', '-', '\x2', '/', '\x2', '\x31', '\x2', '\x33', 
		'\x2', '\x35', '\x2', '\x37', '\x2', '\x39', '\x2', ';', '\x2', '=', '\a', 
		'?', '\x2', '\x41', '\x2', '\x43', '\x2', '\x45', '\x2', 'G', '\x2', 'I', 
		'\b', 'K', '\t', 'M', '\n', 'O', '\v', 'Q', '\f', 'S', '\r', '\x3', '\x2', 
		'\v', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x3', '\x2', '\x32', '\x39', '\x3', '\x2', '\x32', 
		'\x33', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '\f', '\f', ')', 
		')', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x10D', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'M', '\x3', '\x2', '\x2', '\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'Q', '\x3', '\x2', '\x2', '\x2', '\x2', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\x3', 'X', '\x3', '\x2', '\x2', '\x2', '\x5', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\\', '\x3', '\x2', '\x2', '\x2', '\t', '^', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x62', '\x3', '\x2', '\x2', '\x2', '\r', '\x64', 
		'\x3', '\x2', '\x2', '\x2', '\xF', 'x', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x13', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x17', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x95', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\xA7', '\x3', '\x2', '\x2', '\x2', '!', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '#', '\xAC', '\x3', '\x2', '\x2', '\x2', '%', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\xB3', '\x3', '\x2', '\x2', '\x2', 
		')', '\xB7', '\x3', '\x2', '\x2', '\x2', '+', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '-', '\xBE', '\x3', '\x2', '\x2', '\x2', '/', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\xC3', '\x3', '\x2', '\x2', '\x2', '\x33', '\xC7', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xD2', '\x3', '\x2', '\x2', '\x2', '\x39', '\xD4', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xDA', '\x3', '\x2', '\x2', '\x2', '=', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xE2', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\x43', '\xF1', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\xF6', '\x3', '\x2', '\x2', '\x2', 'G', '\xFA', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\xFD', '\x3', '\x2', '\x2', '\x2', 'K', '\x101', 
		'\x3', '\x2', '\x2', '\x2', 'M', '\x103', '\x3', '\x2', '\x2', '\x2', 
		'O', '\x105', '\x3', '\x2', '\x2', '\x2', 'Q', '\x107', '\x3', '\x2', 
		'\x2', '\x2', 'S', '\x10A', '\x3', '\x2', '\x2', '\x2', 'U', 'Y', '\x5', 
		'\x5', '\x3', '\x2', 'V', 'Y', '\x5', '\a', '\x4', '\x2', 'W', 'Y', '\x5', 
		'\t', '\x5', '\x2', 'X', 'U', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', '\x4', 
		'\x3', '\x2', '\x2', '\x2', 'Z', '[', '\t', '\x2', '\x2', '\x2', '[', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\t', '\x3', '\x2', '\x2', 
		']', '\b', '\x3', '\x2', '\x2', '\x2', '^', '_', '\t', '\x4', '\x2', '\x2', 
		'_', '\n', '\x3', '\x2', '\x2', '\x2', '`', '\x63', '\x5', '\r', '\a', 
		'\x2', '\x61', '\x63', '\x5', '\xF', '\b', '\x2', '\x62', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\x31', '\x2', 
		'\x2', '\x65', '\x66', '\a', '\x31', '\x2', '\x2', '\x66', 'j', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'i', '\n', '\x5', '\x2', '\x2', 'h', 'g', '\x3', 
		'\x2', '\x2', '\x2', 'i', 'l', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', '\xE', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'm', 
		'n', '\a', '}', '\x2', '\x2', 'n', 'o', '\x5', '\x11', '\t', '\x2', 'o', 
		'p', '\a', '\x7F', '\x2', '\x2', 'p', 'y', '\x3', '\x2', '\x2', '\x2', 
		'q', 'r', '\a', '*', '\x2', '\x2', 'r', 's', '\a', ',', '\x2', '\x2', 
		's', 't', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x5', '\x11', '\t', '\x2', 
		'u', 'v', '\a', ',', '\x2', '\x2', 'v', 'w', '\a', '+', '\x2', '\x2', 
		'w', 'y', '\x3', '\x2', '\x2', '\x2', 'x', 'm', '\x3', '\x2', '\x2', '\x2', 
		'x', 'q', '\x3', '\x2', '\x2', '\x2', 'y', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'z', '}', '\x5', '\xF', '\b', '\x2', '{', '}', '\v', '\x2', '\x2', 
		'\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', '|', '{', '\x3', '\x2', '\x2', 
		'\x2', '}', '\x80', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x12', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x84', '\x5', '\x5', '\x3', '\x2', '\x82', '\x84', '\x5', '\x15', '\v', 
		'\x2', '\x83', '\x81', '\x3', '\x2', '\x2', '\x2', '\x83', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x88', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x89', '\x5', '\x5', '\x3', '\x2', '\x86', '\x89', '\x5', '\a', '\x4', 
		'\x2', '\x87', '\x89', '\x5', '\x15', '\v', '\x2', '\x88', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8B', '\b', '\n', '\x2', '\x2', '\x8B', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x61', '\x2', '\x2', '\x8D', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x90', '\x5', '\x1D', '\xF', 
		'\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\x5', '\x19', '\r', '\x2', '\x92', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x96', '\x5', '\x1B', '\xE', '\x2', '\x94', '\x96', '\x5', 
		'\x35', '\x1B', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\xA2', '\x5', '#', '\x12', '\x2', '\x98', '\x99', '\x5', 
		'%', '\x13', '\x2', '\x99', '\x9A', '\x5', '\'', '\x14', '\x2', '\x9A', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x5', ')', '\x15', 
		'\x2', '\x9C', '\x9D', '\x5', '+', '\x16', '\x2', '\x9D', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\x5', '/', '\x18', '\x2', '\x9F', 
		'\xA0', '\x5', '\x31', '\x19', '\x2', '\xA0', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\x97', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\xA2', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA6', '\x5', '\x1F', '\x10', '\x2', '\xA4', '\xA6', '\x5', 
		'!', '\x11', '\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\a', '-', '\x2', '\x2', '\xA8', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\a', '/', '\x2', '\x2', '\xAA', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAD', '\x5', '\a', '\x4', '\x2', '\xAC', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '$', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB1', '\a', '&', '\x2', '\x2', '\xB1', '&', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB4', '\x5', '\t', '\x5', '\x2', '\xB3', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '(', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', '(', '\x2', 
		'\x2', '\xB8', '*', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBB', '\x5', 
		'-', '\x17', '\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', ',', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBF', '\t', '\x6', '\x2', '\x2', '\xBF', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\a', '\'', '\x2', '\x2', 
		'\xC1', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC4', '\x5', '\x33', 
		'\x1A', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', 
		'\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', 
		'\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\xC7', '\xC8', '\t', '\a', '\x2', '\x2', '\xC8', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\xC9', '\xCD', '\x5', '#', '\x12', '\x2', 
		'\xCA', '\xCB', '\x5', '\x37', '\x1C', '\x2', '\xCB', '\xCC', '\x5', '#', 
		'\x12', '\x2', '\xCC', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCA', 
		'\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', '\x2', '\x2', '\x2', 
		'\xCE', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD1', '\x5', '\x39', 
		'\x1D', '\x2', '\xD0', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', 
		'\x3', '\x2', '\x2', '\x2', '\xD1', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\xD2', '\xD3', '\a', '\x30', '\x2', '\x2', '\xD3', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\xD4', '\xD6', '\x5', ';', '\x1E', '\x2', '\xD5', '\xD7', 
		'\x5', '\x1D', '\xF', '\x2', '\xD6', '\xD5', '\x3', '\x2', '\x2', '\x2', 
		'\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xD9', '\x5', '#', '\x12', '\x2', '\xD9', ':', 
		'\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', '\t', '\b', '\x2', '\x2', 
		'\xDB', '<', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDF', '\x5', '?', ' ', 
		'\x2', '\xDD', '\xDF', '\x5', '\x45', '#', '\x2', '\xDE', '\xDC', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDE', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE1', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE6', '\x5', '\x43', '\"', '\x2', '\xE3', 
		'\xE5', '\x5', '\x41', '!', '\x2', '\xE4', '\xE3', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\xE6', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE9', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE6', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xEA', '\x5', '\x43', '\"', '\x2', '\xEA', '@', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\xF0', '\n', '\t', '\x2', '\x2', '\xEC', 
		'\xED', '\x5', '\x43', '\"', '\x2', '\xED', '\xEE', '\x5', '\x43', '\"', 
		'\x2', '\xEE', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xEF', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF2', '\a', ')', '\x2', 
		'\x2', '\xF2', '\x44', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF4', '\x5', 
		'G', '$', '\x2', '\xF4', '\xF5', '\x5', '\x1B', '\xE', '\x2', '\xF5', 
		'\xF7', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', '\xF7', '\xF8', '\x3', '\x2', '\x2', '\x2', '\xF8', '\xF6', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xFB', '\a', '%', '\x2', 
		'\x2', '\xFB', 'H', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFE', '\t', 
		'\n', '\x2', '\x2', '\xFD', '\xFC', '\x3', '\x2', '\x2', '\x2', '\xFE', 
		'\xFF', '\x3', '\x2', '\x2', '\x2', '\xFF', '\xFD', '\x3', '\x2', '\x2', 
		'\x2', '\xFF', '\x100', '\x3', '\x2', '\x2', '\x2', '\x100', 'J', '\x3', 
		'\x2', '\x2', '\x2', '\x101', '\x102', '\a', '=', '\x2', '\x2', '\x102', 
		'L', '\x3', '\x2', '\x2', '\x2', '\x103', '\x104', '\a', '*', '\x2', '\x2', 
		'\x104', 'N', '\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\a', '+', 
		'\x2', '\x2', '\x106', 'P', '\x3', '\x2', '\x2', '\x2', '\x107', '\x108', 
		'\a', '\x30', '\x2', '\x2', '\x108', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\x109', '\x10B', '\v', '\x2', '\x2', '\x2', '\x10A', '\x109', '\x3', 
		'\x2', '\x2', '\x2', '\x10B', '\x10C', '\x3', '\x2', '\x2', '\x2', '\x10C', 
		'\x10D', '\x3', '\x2', '\x2', '\x2', '\x10C', '\x10A', '\x3', '\x2', '\x2', 
		'\x2', '\x10D', 'T', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x2', 'X', '\x62', 
		'j', 'x', '|', '~', '\x83', '\x88', '\x8F', '\x95', '\xA1', '\xA5', '\xAE', 
		'\xB5', '\xBC', '\xC5', '\xCD', '\xD0', '\xD6', '\xDE', '\xE0', '\xE6', 
		'\xEF', '\xF8', '\xFF', '\x10C', '\x3', '\x3', '\n', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
